server:
  port: 9601
#服务名字
spring:
  application:
    name: configServer
  cloud:
    config:
      server:
        git:
#git 仓库的地址
          uri: https://github.com/overduegril/chener.git
#git 仓库的账号密码
          username: 1486733900@qq.com
          password: gdw966471
          label: master #配置仓库的分支
#加入注册中心，实现高可用
eureka:
  client:
    service-url:
       defaultZone: http://wosz:147258369@localhost:9600/eureka/
