server:
  port: 9600
spring:
  application:
    name: eurekaServer
  security:
    user:
      password: 147258369
      name: wosz
eureka:
  server:
    peer-node-read-timeout-ms: 3000
    enable-self-preservation: false
#  instance:
#    prefer-ip-address: true
#    instance-id: ${spring.cloud.client.ip-address}:${server.port}
  client:
    registerWithEureka: false  #单机
    fetchRegistry: false  #自我注册实现集群
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://10.0.3.4:9600/eureka/
